CREATE TABLE register(id SERIAL PRIMARY KEY,username VARCHAR NOT NULL ,password VARCHAR NOT NULL );
 
CREATE TABLE books(id SERIAL PRIMARY KEY,isbn VARCHAR UNIQUE NOT NULL , title VARCHAR NOT NULL , author VARCHAR NOT NULL , year INTEGER NOT NULL);

CREATE TABLE reviews(id SERIAL PRIMARY KEY,register_id INTEGER REFERENCES register(id) NOT NULL,book_id INTEGER REFERENCES books(id),review VARCHAR NOT NULL, rating INTEGER CHECK (rating <= 5));
